name: test

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  ##############################################################################
  ShellLint:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@master

    - name: Prep
      run: |
        sudo apt-get install -y shellcheck

    - name: Shellcheck
      run: |
        shellcheck ./configure

  ##############################################################################
  TestMatrix:
    strategy:
      matrix:
        lua-version: ["5.4", "luajit-2.1"]
        os: ["ubuntu-latest", "macos-13"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master

    - uses: hishamhm/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.lua-version }}

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Prep
      run: |
        luarocks install busted
        luarocks install cluacov
        luarocks install busted-htest

    - name: Unit Test
      run: |
        eval $(luarocks path)
        busted -o htest --exclude-tags=git,integration --verbose -Xhelper "lua_dir=$(luarocks config variables.LUA_DIR),ci"
        busted -o htest --exclude-tags=git,integration --verbose -Xhelper "lua_dir=$(luarocks config variables.LUA_DIR),ci,env=full"

    - name: Integration Test
      run: |
        eval $(luarocks path)
        busted -o htest --exclude-tags=ssh,gpg,git,unit,quick --verbose -Xhelper "lua_dir=$(luarocks config variables.LUA_DIR),ci"
        busted -o htest --exclude-tags=ssh,gpg,git,unit,quick --verbose -Xhelper "lua_dir=$(luarocks config variables.LUA_DIR),ci,env=full"

  ##############################################################################
  SmokeTest:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@master

    - uses: hishamhm/gh-actions-lua@master
      with:
        luaVersion: "5.4"

    - name: Smoke Test
      run: |
        ./configure
        ./makedist dev
        ./smoke_test.sh luarocks-dev.tar.gz
